// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/proxy/http/responseinstance.go
//
// Generated by this command:
//
//	mockgen -source=../app/proxy/http/responseinstance.go -destination=../mock/app/proxy/http/responseinstance.go -package=mockhttpproxy
//

// Package mockhttpproxy is a generated GoMock package.
package mockhttpproxy

import (
	gomock "go.uber.org/mock/gomock"
)

// MockResponseInstanceInterface is a mock of ResponseInstanceInterface interface.
type MockResponseInstanceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockResponseInstanceInterfaceMockRecorder
}

// MockResponseInstanceInterfaceMockRecorder is the mock recorder for MockResponseInstanceInterface.
type MockResponseInstanceInterfaceMockRecorder struct {
	mock *MockResponseInstanceInterface
}

// NewMockResponseInstanceInterface creates a new mock instance.
func NewMockResponseInstanceInterface(ctrl *gomock.Controller) *MockResponseInstanceInterface {
	mock := &MockResponseInstanceInterface{ctrl: ctrl}
	mock.recorder = &MockResponseInstanceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseInstanceInterface) EXPECT() *MockResponseInstanceInterfaceMockRecorder {
	return m.recorder
}
