// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/proxy/debug/buildinfoinstance.go
//
// Generated by this command:
//
//	mockgen -source=../app/proxy/debug/buildinfoinstance.go -destination=../mock/app/proxy/debug/buildinfoinstance.go -package=mockdebugproxy
//

// Package mockdebugproxy is a generated GoMock package.
package mockdebugproxy

import (
	gomock "go.uber.org/mock/gomock"
)

// MockBuildInfoInstanceInterface is a mock of BuildInfoInstanceInterface interface.
type MockBuildInfoInstanceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBuildInfoInstanceInterfaceMockRecorder
}

// MockBuildInfoInstanceInterfaceMockRecorder is the mock recorder for MockBuildInfoInstanceInterface.
type MockBuildInfoInstanceInterfaceMockRecorder struct {
	mock *MockBuildInfoInstanceInterface
}

// NewMockBuildInfoInstanceInterface creates a new mock instance.
func NewMockBuildInfoInstanceInterface(ctrl *gomock.Controller) *MockBuildInfoInstanceInterface {
	mock := &MockBuildInfoInstanceInterface{ctrl: ctrl}
	mock.recorder = &MockBuildInfoInstanceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildInfoInstanceInterface) EXPECT() *MockBuildInfoInstanceInterfaceMockRecorder {
	return m.recorder
}
