version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/pkg"
    schedule:
      interval: "weekly"
