// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/proxy/user/userinstance.go
//
// Generated by this command:
//
//	mockgen -source=../app/proxy/user/userinstance.go -destination=../mock/app/proxy/user/userinstance.go -package=mockuserproxy
//

// Package mockuserproxy is a generated GoMock package.
package mockuserproxy

import (
	gomock "go.uber.org/mock/gomock"
)

// MockUserInstanceInterface is a mock of UserInstanceInterface interface.
type MockUserInstanceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserInstanceInterfaceMockRecorder
}

// MockUserInstanceInterfaceMockRecorder is the mock recorder for MockUserInstanceInterface.
type MockUserInstanceInterfaceMockRecorder struct {
	mock *MockUserInstanceInterface
}

// NewMockUserInstanceInterface creates a new mock instance.
func NewMockUserInstanceInterface(ctrl *gomock.Controller) *MockUserInstanceInterface {
	mock := &MockUserInstanceInterface{ctrl: ctrl}
	mock.recorder = &MockUserInstanceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInstanceInterface) EXPECT() *MockUserInstanceInterfaceMockRecorder {
	return m.recorder
}
