// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/proxy/fs/fileinfoinstance.go
//
// Generated by this command:
//
//	mockgen -source=../app/proxy/fs/fileinfoinstance.go -destination=../mock/app/proxy/fs/fileinfoinstance.go -package=mockfsproxy
//

// Package mockfsproxy is a generated GoMock package.
package mockfsproxy

import (
	gomock "go.uber.org/mock/gomock"
)

// MockFileInfoInstanceInterface is a mock of FileInfoInstanceInterface interface.
type MockFileInfoInstanceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileInfoInstanceInterfaceMockRecorder
}

// MockFileInfoInstanceInterfaceMockRecorder is the mock recorder for MockFileInfoInstanceInterface.
type MockFileInfoInstanceInterfaceMockRecorder struct {
	mock *MockFileInfoInstanceInterface
}

// NewMockFileInfoInstanceInterface creates a new mock instance.
func NewMockFileInfoInstanceInterface(ctrl *gomock.Controller) *MockFileInfoInstanceInterface {
	mock := &MockFileInfoInstanceInterface{ctrl: ctrl}
	mock.recorder = &MockFileInfoInstanceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileInfoInstanceInterface) EXPECT() *MockFileInfoInstanceInterfaceMockRecorder {
	return m.recorder
}
