// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/proxy/rand.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/proxy/rand.go -destination=./pkg/proxy/rand_mock.go -package=proxy
//

// Package proxy is a generated GoMock package.
package proxy

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRand is a mock of Rand interface.
type MockRand struct {
	ctrl     *gomock.Controller
	recorder *MockRandMockRecorder
	isgomock struct{}
}

// MockRandMockRecorder is the mock recorder for MockRand.
type MockRandMockRecorder struct {
	mock *MockRand
}

// NewMockRand creates a new mock instance.
func NewMockRand(ctrl *gomock.Controller) *MockRand {
	mock := &MockRand{ctrl: ctrl}
	mock.recorder = &MockRandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRand) EXPECT() *MockRandMockRecorder {
	return m.recorder
}

// Intn mocks base method.
func (m *MockRand) Intn(n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intn", n)
	ret0, _ := ret[0].(int)
	return ret0
}

// Intn indicates an expected call of Intn.
func (mr *MockRandMockRecorder) Intn(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intn", reflect.TypeOf((*MockRand)(nil).Intn), n)
}
