// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/presentation/cli/jrp/formatter/formatter.go
//
// Generated by this command:
//
//	mockgen -source=./app/presentation/cli/jrp/formatter/formatter.go -destination=./app/presentation/cli/jrp/formatter/formatter_mock.go -package=formatter
//

// Package formatter is a generated GoMock package.
package formatter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFormatter is a mock of Formatter interface.
type MockFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterMockRecorder
	isgomock struct{}
}

// MockFormatterMockRecorder is the mock recorder for MockFormatter.
type MockFormatterMockRecorder struct {
	mock *MockFormatter
}

// NewMockFormatter creates a new mock instance.
func NewMockFormatter(ctrl *gomock.Controller) *MockFormatter {
	mock := &MockFormatter{ctrl: ctrl}
	mock.recorder = &MockFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormatter) EXPECT() *MockFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method.
func (m *MockFormatter) Format(result any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", result)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Format indicates an expected call of Format.
func (mr *MockFormatterMockRecorder) Format(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockFormatter)(nil).Format), result)
}
