// Code generated by MockGen. DO NOT EDIT.
// Source: internal/spinnerservice/spinner_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/spinnerservice/spinner_service.go -destination=mock/spinnerservice/spinner_service.go -package=mock_spinnerservice
//

// Package mock_spinnerservice is a generated GoMock package.
package mock_spinnerservice

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSpinnerService is a mock of SpinnerService interface.
type MockSpinnerService struct {
	ctrl     *gomock.Controller
	recorder *MockSpinnerServiceMockRecorder
}

// MockSpinnerServiceMockRecorder is the mock recorder for MockSpinnerService.
type MockSpinnerServiceMockRecorder struct {
	mock *MockSpinnerService
}

// NewMockSpinnerService creates a new mock instance.
func NewMockSpinnerService(ctrl *gomock.Controller) *MockSpinnerService {
	mock := &MockSpinnerService{ctrl: ctrl}
	mock.recorder = &MockSpinnerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpinnerService) EXPECT() *MockSpinnerServiceMockRecorder {
	return m.recorder
}

// SetColor mocks base method.
func (m *MockSpinnerService) SetColor(colors ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range colors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetColor", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetColor indicates an expected call of SetColor.
func (mr *MockSpinnerServiceMockRecorder) SetColor(colors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetColor", reflect.TypeOf((*MockSpinnerService)(nil).SetColor), colors...)
}

// SetSuffix mocks base method.
func (m *MockSpinnerService) SetSuffix(suffix string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSuffix", suffix)
}

// SetSuffix indicates an expected call of SetSuffix.
func (mr *MockSpinnerServiceMockRecorder) SetSuffix(suffix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSuffix", reflect.TypeOf((*MockSpinnerService)(nil).SetSuffix), suffix)
}

// Start mocks base method.
func (m *MockSpinnerService) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockSpinnerServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSpinnerService)(nil).Start))
}

// Stop mocks base method.
func (m *MockSpinnerService) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSpinnerServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSpinnerService)(nil).Stop))
}
