// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/proxy/cobra/positionalargsinstance.go
//
// Generated by this command:
//
//	mockgen -source=../app/proxy/cobra/positionalargsinstance.go -destination=../mock/app/proxy/cobra/positionalargsinstance.go -package=mockcobraproxy
//

// Package mockcobraproxy is a generated GoMock package.
package mockcobraproxy

import (
	gomock "go.uber.org/mock/gomock"
)

// MockPositionalArgsInstanceInterface is a mock of PositionalArgsInstanceInterface interface.
type MockPositionalArgsInstanceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPositionalArgsInstanceInterfaceMockRecorder
}

// MockPositionalArgsInstanceInterfaceMockRecorder is the mock recorder for MockPositionalArgsInstanceInterface.
type MockPositionalArgsInstanceInterfaceMockRecorder struct {
	mock *MockPositionalArgsInstanceInterface
}

// NewMockPositionalArgsInstanceInterface creates a new mock instance.
func NewMockPositionalArgsInstanceInterface(ctrl *gomock.Controller) *MockPositionalArgsInstanceInterface {
	mock := &MockPositionalArgsInstanceInterface{ctrl: ctrl}
	mock.recorder = &MockPositionalArgsInstanceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPositionalArgsInstanceInterface) EXPECT() *MockPositionalArgsInstanceInterfaceMockRecorder {
	return m.recorder
}
