// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/proxy/pflag/pflagproxy.go
//
// Generated by this command:
//
//	mockgen -source=../app/proxy/pflag/pflagproxy.go -destination=../mock/app/proxy/pflag/pflagproxy.go -package=mockpflagproxy
//

// Package mockpflagproxy is a generated GoMock package.
package mockpflagproxy

import (
	gomock "go.uber.org/mock/gomock"
)

// MockPflag is a mock of Pflag interface.
type MockPflag struct {
	ctrl     *gomock.Controller
	recorder *MockPflagMockRecorder
}

// MockPflagMockRecorder is the mock recorder for MockPflag.
type MockPflagMockRecorder struct {
	mock *MockPflag
}

// NewMockPflag creates a new mock instance.
func NewMockPflag(ctrl *gomock.Controller) *MockPflag {
	mock := &MockPflag{ctrl: ctrl}
	mock.recorder = &MockPflagMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPflag) EXPECT() *MockPflagMockRecorder {
	return m.recorder
}
